//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KT7.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adress
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Adress()
        {
            this.PartnerImport = new HashSet<PartnerImport>();
        }
    
        public int Id { get; set; }
        public int IdArticle { get; set; }
        public int IdOblast { get; set; }
        public int Id_Town { get; set; }
        public int Id_Street { get; set; }
        public int Num_house { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual Oblast Oblast { get; set; }
        public virtual Street Street { get; set; }
        public virtual Town Town { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnerImport> PartnerImport { get; set; }
    }
}
