//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KT7.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterProductImport
    {
        public int Id { get; set; }
        public int IdProduction { get; set; }
        public int IdPartner { get; set; }
        public int ProductNum { get; set; }
        public System.DateTime SaleData { get; set; }
    
        public virtual PartnerName PartnerName { get; set; }
        public virtual Production Production { get; set; }
    }
}
