//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KT7.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialTypeProduct
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public double ProcentOfUsability { get; set; }
    }
}
