//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KT7.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerImport
    {
        public int Id { get; set; }
        public int IdTypePartner { get; set; }
        public int IdPartnerName { get; set; }
        public int IdDirector { get; set; }
        public string Email { get; set; }
        public string Phone_Number { get; set; }
        public int IdAdress { get; set; }
        public long INN { get; set; }
        public int Rating { get; set; }
    
        public virtual Adress Adress { get; set; }
        public virtual Director Director { get; set; }
        public virtual PartnerName PartnerName { get; set; }
        public virtual PartnerType PartnerType { get; set; }
    }
}
