//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KT7.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTypeImport
    {
        public int Id { get; set; }
        public int TypeProduction { get; set; }
        public double AVGTypeProduction { get; set; }
    
        public virtual TypeProduct TypeProduct { get; set; }
    }
}
